services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/outputs:/app/backend/outputs
      - ./backend/models:/app/backend/models

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_MAPBOX_TOKEN=${REACT_APP_MAPBOX_TOKEN}
      - REACT_APP_REQUIRE_LOGIN=${REACT_APP_REQUIRE_LOGIN:-false}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    depends_on:
      - backend
